# Generated by Django 5.0.7 on 2024-07-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('main', models.CharField(max_length=50)),
                ('temp', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('dt', models.DateTimeField()),
            ],
        ),
    ]
